name: Furikake
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7763588598463684
title: Furikake dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
